---
apiVersion: v1
kind: Service
metadata:
  name: srsran-gnb-metrics
  labels:
    app: srsran
    component: gnb
spec:
  selector:
    app: srsran
    component: gnb
  ports:
    - name: websocket
      port: 8001
      targetPort: 8001
      protocol: TCP
  type: ClusterIP
